#!/usr/bin/env php
<?php

declare(strict_types=1);

use WPMigration\Console\ApplicationFactory;

require __DIR__ . '/vendor/autoload.php';

$application = ApplicationFactory::create(__DIR__);
$application->run();
